language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip install -e .
    - pip install flake8
    - pip install coveralls
    - npm install -g mocha-headless-chrome
script:
    - make test
    - flake8
after_success:
    - coveralls
